### ISSUE TITLE
GetType not useful on reference item entity

### ISSUE THREAD

**Issue by KirkDiggler** [fadedpez/dnd5e-api#96]
entity Reference Item does not need a GetType() function and the json tag is misleading
[this code](https://github.com/fadedpez/dnd5e-api/blob/main/entities/reference_item.go#L11) is not needed as the [serializer](https://github.com/fadedpez/dnd5e-api/blob/main/clients/dnd5e/serializers.go#L888) does the conversion for us.
Additionally the json [tag](https://github.com/fadedpez/dnd5e-api/blob/main/entities/reference_item.go#L8) should match the field name

**Comment by fadedpez** [comment]
fixed in pr: fadedpez/dnd5e-api/pull/98
